# Generated by Django 5.2.6 on 2026-01-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_tenant_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconfiguration',
            name='shipping_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
