# Generated by Django 5.2.6 on 2026-01-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_tenantconfiguration_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantconfiguration',
            name='shipping_price',
        ),
    ]
