# Generated by Django 5.2.6 on 2026-03-23 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_tenantconfiguration_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
