# Generated by ChatGPT on 2026-03-28

from django.db import migrations


def seed_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('users', 'SubscriptionPlan')

    defaults = [
        {
            'code': 'basic',
            'name': 'Plan Básico',
            'description': 'Ideal para empezar: control básico, un usuario y límites estándar.',
            'price': '0.00',
            'max_users': 1,
            'max_products': 50,
            'max_categories': 10,
            'max_transactions_per_month': 100,
            'enable_basic_dashboard': True,
            'enable_basic_sales': True,
            'enable_basic_stats': True,
            'enable_user_management': False,
            'enable_advanced_sales_analysis': False,
            'enable_inventory_management': False,
            'enable_detailed_reports': False,
            'enable_third_party_integrations': False,
            'enable_supplier_management': False,
            'enable_daily_backups': False,
            'enable_web_store': False,
            'enable_custom_domain': False,
            'enable_marketing_tools': False,
            'enable_api_access': False,
            'enable_priority_support': False,
            'enable_whatsapp_notifications': False,
            'enable_electronic_invoicing': False,
        },
        {
            'code': 'medium',
            'name': 'Plan Medio',
            'description': 'Para negocios en crecimiento: inventario, reportes y más usuarios.',
            'price': '49900.00',
            'max_users': 5,
            'max_products': 500,
            'max_categories': 50,
            'max_transactions_per_month': 2000,
            'enable_basic_dashboard': True,
            'enable_basic_sales': True,
            'enable_basic_stats': True,
            'enable_user_management': True,
            'enable_advanced_sales_analysis': True,
            'enable_inventory_management': True,
            'enable_detailed_reports': True,
            'enable_third_party_integrations': True,
            'enable_supplier_management': True,
            'enable_daily_backups': True,
            'enable_web_store': False,
            'enable_custom_domain': False,
            'enable_marketing_tools': False,
            'enable_api_access': False,
            'enable_priority_support': False,
            'enable_whatsapp_notifications': False,
            'enable_electronic_invoicing': False,
        },
        {
            'code': 'advanced',
            'name': 'Plan Avanzado',
            'description': 'Todo incluido: tienda web, dominio, API, marketing y soporte prioritario.',
            'price': '99900.00',
            'max_users': -1,
            'max_products': -1,
            'max_categories': -1,
            'max_transactions_per_month': -1,
            'enable_basic_dashboard': True,
            'enable_basic_sales': True,
            'enable_basic_stats': True,
            'enable_user_management': True,
            'enable_advanced_sales_analysis': True,
            'enable_inventory_management': True,
            'enable_detailed_reports': True,
            'enable_third_party_integrations': True,
            'enable_supplier_management': True,
            'enable_daily_backups': True,
            'enable_web_store': True,
            'enable_custom_domain': True,
            'enable_marketing_tools': True,
            'enable_api_access': True,
            'enable_priority_support': True,
            'enable_whatsapp_notifications': True,
            'enable_electronic_invoicing': True,
        },
    ]

    for d in defaults:
        code = d['code']
        values = {k: v for k, v in d.items() if k != 'code'}
        SubscriptionPlan.objects.update_or_create(code=code, defaults=values)


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_tenant_has_paid'),
    ]

    operations = [
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
    ]

