# Generated by ChatGPT on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0016_seed_subscription_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('actor_role', models.CharField(blank=True, default='', max_length=30)),
                ('action', models.CharField(max_length=40)),
                ('resource_type', models.CharField(blank=True, default='', max_length=60)),
                ('resource_id', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='auth.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='users.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', '-created_at'], name='ual_tenant_created_idx'),
                    models.Index(fields=['tenant', 'actor', '-created_at'], name='ual_tenant_actor_idx'),
                    models.Index(fields=['tenant', 'action', '-created_at'], name='ual_tenant_action_idx'),
                    models.Index(fields=['tenant', 'resource_type', '-created_at'], name='ual_tenant_res_idx'),
                ],
            },
        ),
    ]
