# Generated by ChatGPT on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion
import users.models_tenant_config


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_tenant_activity_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(blank=True, default='', max_length=150)),
                ('sender_role', models.CharField(blank=True, default='', max_length=30)),
                ('audio', models.FileField(upload_to=users.models_tenant_config._support_audio_path)),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to='auth.user')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to='users.tenant')),
            ],
            options={
                'indexes': [
                    models.Index(fields=['tenant', '-created_at'], name='tsm_tenant_created_idx'),
                    models.Index(fields=['tenant', 'sender_role', '-created_at'], name='tsm_tenant_role_idx'),
                ],
            },
        ),
    ]

