# Generated by ChatGPT on 2026-03-30

from django.db import migrations, models
import users.models_tenant_config


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0018_tenant_support_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsupportmessage',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='tenantsupportmessage',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=users.models_tenant_config._support_audio_path),
        ),
    ]
