# Generated by ChatGPT on 2026-03-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0019_support_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSupportChatState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_id', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_states', to='users.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_chat_states', to='auth.user')),
            ],
            options={
                'unique_together': {('tenant', 'user')},
                'indexes': [
                    models.Index(fields=['tenant', 'user'], name='tscs_tenant_user_idx'),
                    models.Index(fields=['user', '-updated_at'], name='tscs_user_updated_idx'),
                ],
            },
        ),
    ]

