# Generated by Django 5.2.6 on 2026-04-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_support_chat_state'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tenantactivitylog',
            new_name='users_tenan_tenant__e47f79_idx',
            old_name='ual_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantactivitylog',
            new_name='users_tenan_tenant__e1a1af_idx',
            old_name='ual_tenant_actor_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantactivitylog',
            new_name='users_tenan_tenant__8dc72c_idx',
            old_name='ual_tenant_action_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantactivitylog',
            new_name='users_tenan_tenant__62345e_idx',
            old_name='ual_tenant_res_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsupportchatstate',
            new_name='users_tenan_tenant__5d00c2_idx',
            old_name='tscs_tenant_user_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsupportchatstate',
            new_name='users_tenan_user_id_11f3f7_idx',
            old_name='tscs_user_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsupportmessage',
            new_name='users_tenan_tenant__43b02a_idx',
            old_name='tsm_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tenantsupportmessage',
            new_name='users_tenan_tenant__a10adc_idx',
            old_name='tsm_tenant_role_idx',
        ),
        migrations.AlterField(
            model_name='tenantpermission',
            name='permission',
            field=models.CharField(choices=[('enforce_permissions', 'Enforce Permissions'), ('view_products', 'View Products'), ('create_products', 'Create Products'), ('edit_products', 'Edit Products'), ('delete_products', 'Delete Products'), ('view_categories', 'View Categories'), ('create_categories', 'Create Categories'), ('edit_categories', 'Edit Categories'), ('delete_categories', 'Delete Categories'), ('view_clients', 'View Clients'), ('create_clients', 'Create Clients'), ('edit_clients', 'Edit Clients'), ('delete_clients', 'Delete Clients'), ('view_sales', 'View Sales'), ('create_sales', 'Create Sales'), ('edit_sales', 'Edit Sales'), ('delete_sales', 'Delete Sales'), ('view_orders', 'View Orders'), ('edit_orders', 'Edit Orders'), ('delete_orders', 'Delete Orders'), ('view_services', 'View Services'), ('create_services', 'Create Services'), ('edit_services', 'Edit Services'), ('delete_services', 'Delete Services'), ('view_cashbox', 'View Cashbox'), ('edit_cashbox', 'Edit Cashbox'), ('view_web', 'View Web'), ('edit_web', 'Edit Web'), ('view_reports', 'View Reports'), ('manage_users', 'Manage Users'), ('manage_settings', 'Manage Settings')], max_length=50),
        ),
    ]
