# Generated by Django 5.2.6 on 2026-01-13 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_third_party_cost'),
        ('users', '0014_remove_tenantconfiguration_shipping_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_definitions/')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estimated_duration', models.CharField(blank=True, help_text='Ej: 2 horas, 3 días', max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='service_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicedefinition'),
        ),
    ]
