# Generated by Django 5.2.6 on 2026-03-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_address_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('person', 'Persona Natural'), ('company', 'Empresa')], default='person', max_length=10),
        ),
    ]
