# Generated by Django 5.2.6 on 2026-01-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_appsettings_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='pickup_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
