# Generated by Django 5.2.6 on 2026-02-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_appsettings_free_shipping_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='google_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
