# Generated by Django 5.2.6 on 2026-03-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_appsettings_google_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='meta_config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
