# Generated by Django 5.2.6 on 2026-03-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_appsettings_meta_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appsettings',
            name='meta_config',
        ),
    ]
