# Generated by Django 5.2.6 on 2026-01-12 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0001_initial'),
        ('users', '0014_remove_tenantconfiguration_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicinvoice',
            name='dian_errors',
        ),
        migrations.RemoveField(
            model_name='electronicinvoice',
            name='dian_response',
        ),
        migrations.RemoveField(
            model_name='electronicinvoice',
            name='retry_count',
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID en el sistema externo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='external_status_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electronicinvoice',
            name='provider',
            field=models.CharField(default='dian', help_text='dian or alegra', max_length=20),
        ),
        migrations.AlterField(
            model_name='electronicinvoice',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='einvoicing.dianresolution'),
        ),
        migrations.CreateModel(
            name='AlegraCompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Correo de acceso a Alegra', max_length=254)),
                ('api_key', models.CharField(help_text='Token de API de Alegra', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alegra_config', to='users.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AlegraMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Cliente'), ('product', 'Producto')], max_length=20)),
                ('internal_id', models.PositiveIntegerField()),
                ('alegra_id', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'type', 'internal_id'], name='einvoicing__tenant__4b2719_idx')],
                'unique_together': {('tenant', 'type', 'internal_id')},
            },
        ),
    ]
