# Generated by Django 6.0.3 on 2026-03-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('einvoicing', '0002_remove_electronicinvoice_dian_errors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alegracompanyconfig',
            name='tenant',
        ),
        migrations.AlterUniqueTogether(
            name='alegramapping',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='alegramapping',
            name='einvoicing__tenant__4b2719_idx',
        ),
        migrations.AlterField(
            model_name='electronicinvoice',
            name='provider',
            field=models.CharField(default='dian', max_length=20),
        ),
        migrations.DeleteModel(
            name='AlegraCompanyConfig',
        ),
        migrations.DeleteModel(
            name='AlegraMapping',
        ),
    ]
