# Generated by Django 5.2.6 on 2026-03-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_saleitem_setnull_color_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
