# Generated by Django 5.2.6 on 2026-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de compra/costo del producto', max_digits=10),
        ),
    ]
