# Generated by Django 5.2.6 on 2026-03-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_productsku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Si es borrador, se permiten campos incompletos'),
        ),
    ]
